- name: virtualbox | main.yml >> virtualbox dependencies present
  apt: package={{ item }} state=present
  with_items:
    - "linux-headers-{{ ansible_kernel }}"
    - dkms
    - build-essential
    - linux-headers-generic
  tags: virtualbox

- name: virtualbox | ensure download directory
  file: path=/opt/download state=directory

- name: virtualbox | main.yml >> download virtualbox guest additions iso
  get_url: url={{ virtualbox.guest_additions.iso_url }} dest={{ virtualbox.guest_additions.iso_dir }}/VBoxGuestAdditions_{{ virtualbox.guest_additions.version }}.iso timeout=240
  tags: virtualbox

- name: virtualbox | main.yml >> ensure mount dir exists
  file: path={{ virtualbox.guest_additions.iso_mountdir }}/VBoxGuestAdditions_{{ virtualbox.guest_additions.version }} state=directory
  tags: virtualbox

- name: virtualbox | main.yml >> mount virtualbox guest additions iso
  command: mount {{ virtualbox.guest_additions.iso_dir }}/VBoxGuestAdditions_{{ virtualbox.guest_additions.version }}.iso -o loop {{ virtualbox.guest_additions.iso_mountdir }}/VBoxGuestAdditions_{{ virtualbox.guest_additions.version }}
  register: virtualbox_guest_additions_mounted
  tags: virtualbox

- name: virtualbox | main.yml >> virtualbox guest additions present
  command: "{{ virtualbox.guest_additions.iso_mountdir }}/VBoxGuestAdditions_{{ virtualbox.guest_additions.version }}/VBoxLinuxAdditions.run --nox11 -- --force creates=/etc/init.d/vboxadd"
  ignore_errors: True
  tags: virtualbox

- name: virtualbox | main.yml >> umount virtualbox guest additions iso
  shell: umount {{ virtualbox.guest_additions.iso_mountdir }}/VBoxGuestAdditions_{{ virtualbox.guest_additions.version }} removes={{ virtualbox.guest_additions.iso_mountdir }}/VBoxGuestAdditions_{{ virtualbox.guest_additions.version }}
  when: virtualbox_guest_additions_mounted.changed
  tags: virtualbox
